# Generated by Django 3.2.13 on 2022-07-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apinews',
            name='articles',
        ),
        migrations.AddField(
            model_name='apinews',
            name='name',
            field=models.CharField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='apinews',
            name='url',
            field=models.URLField(default='null', max_length=1000),
        ),
    ]
