# Generated by Django 3.2.13 on 2022-07-14 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20220712_2326'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APInews',
        ),
    ]
